import ESTILOS from "./estilos";

const RESTAURANT = [
    {
        name: "Restaurante 1",
        id: 1,
        descripcion: "Este es el restaurante numero 1 que fue utilizado como sujeto de prueba para exportar un array de objetos que contenga toda la informacion de ",
        estilo: 0,
        imgURL: "/Restaurantes/1.webp",
        link: "/Restaurante1",
        handleLink: "Restaurante1",
    },
    {
        name: "Restaurante 2",
        id: 2,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 1,
        imgURL: "/Restaurantes/2.webp",
        link: "/Restaurante2",
        handleLink: "Restaurante2",
    },
    {
        name: "Restaurante 3",
        id: 3,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 2,
        imgURL: "/Restaurantes/3.webp",
        link: "/Restaurante3",
        handleLink: "Restaurante3",
    },
    {
        name: "Restaurante 4",
        id: 4,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 3,
        imgURL: "/Restaurantes/4.webp",
        link: "/Restaurante4",
        handleLink: "Restaurante4",
    },
    {
        name: "Restaurante 5",
        id: 5,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 4,
        imgURL: "/Restaurantes/5.webp",
        link: "/Restaurante5",
        handleLink: "Restaurante5",
    },
    {
        name: "Restaurante 6",
        id: 6,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 3,
        imgURL: "/Restaurantes/6.webp",
        link: "/Restaurante6",
        handleLink: "Restaurante6",
    },
    {
        name: "Restaurante 7",
        id: 7,
        descripcion: "descripcion de la 2 la 2 tiene una descripcion muy descriptiva para descripcionar la descripcion que debe ser descrita porque sinceramente aaa",
        estilo: 3,
        imgURL: "/Restaurantes/7.webp",
        link: "/Restaurante7",
        handleLink: "Restaurante7",
    },
];
export default RESTAURANT;
