const RESTAURANT = [
    {
        id: 1,
        name: "Sabores del Caribe",
        descripcion: "Un lugar que celebra la auténtica cocina caribeña con sazón dominicano.",
        estilo: 0,
        imgURL: "/Restaurantes/1.webp",
        link: "/Restaurante1",
        handleLink: "Restaurante1",
        descripcionLarga:
            "En Sabores del Caribe, cada plato refleja la tradición dominicana con un toque moderno. Aquí se disfruta de mariscos frescos, carnes a la parrilla y guarniciones criollas que enamoran desde la primera probada.",
        ultraLargeDesc:
            "Sabores del Caribe es mucho más que un restaurante: es una experiencia gastronómica que transporta a sus comensales directamente al corazón de la cocina dominicana tradicional. Fundado en 1998 por la familia Hernández, este establecimiento ha mantenido por décadas las recetas auténticas heredadas de generaciones pasadas, combinándolas con técnicas culinarias modernas que realzan los sabores sin perder la esencia caribeña. Cada plato que sale de nuestra cocina cuenta una historia: desde el aroma embriagador del sancocho de siete carnes que slow-cookea por horas hasta la textura perfecta del mangú preparado con plátanos verdes seleccionados manualmente. Nuestros mariscos llegan diariamente desde las costas de Samaná y Puerto Plata, garantizando una frescura incomparable en cada bocado de nuestro pescado con coco o la langosta a la plancha. El ambiente acogedor, decorado con artesanías locales y colores vibrantes que reflejan la cultura dominicana, complementa perfectamente la experiencia sensorial que ofrecemos. Contamos con un equipo de chefs apasionados que no solo dominan las técnicas culinarias, sino que comprenden la importancia cultural de cada ingrediente y cada preparación. Nuestra filosofía se basa en tres pilares fundamentales: autenticidad en los sabores, calidad en los ingredientes y calidez en el servicio. Sabores del Caribe no es simplemente un lugar para comer; es un espacio donde las tradiciones se mantienen vivas, donde cada comida se convierte en un festín familiar y donde los recuerdos se crean alrededor de una mesa llena de los auténticos sabores que definen la rica herencia culinaria de República Dominicana.",
    },
    {
        id: 2,
        name: "Rápido y Rico",
        descripcion: "Comida rápida hecha con ingredientes frescos y calidad casera.",
        estilo: 1,
        imgURL: "/Restaurantes/2.webp",
        link: "/Restaurante2",
        handleLink: "Restaurante2",
        descripcionLarga: "Rápido y Rico ofrece hamburguesas, pizzas y papas fritas que conquistan por su sabor y frescura. Ideal para quienes buscan una comida rápida sin perder calidad.",
        ultraLargeDesc:
            "Rápido y Rico nació en 2005 con la visión de revolucionar el concepto de comida rápida en República Dominicana, demostrando que la velocidad no está reñida con la calidad ni el sabor auténtico. Nuestras hamburguesas son el orgullo de la casa, elaboradas con carne 100% premium de res dominicana, molida diariamente y sazonada con nuestra mezcla secreta de especias que incluye un toque de cilantro y ajo criollo. Cada pan es horneado artesanalmente cada mañana, garantizando esa textura esponjosa por dentro y crujiente por fuera que tanto caracteriza a nuestras creaciones. Las papas fritas se cortan manualmente y se fríen en aceite de girasol de primera calidad, resultando en ese dorado perfecto y ese crujido irresistible. Nuestra pizza sigue la tradición napolitana con masa fermentada 48 horas, pero con ingredientes locales como queso de hoja artesanal y longaniza criolla. El ambiente vibrante y juvenil, con música caribeña de fondo y atención ágil pero cordial, hace de Rápido y Rico el lugar preferido para familias, grupos de amigos y trabajadores que buscan una experiencia gastronómica satisfactoria sin largas esperas. Cada plato que servimos lleva el sello de calidad Rápido y Rico: ingredientes frescos, preparaciones caseras y ese toque dominicano que nos hace únicos.",
    },
    {
        id: 3,
        name: "El Fogón Parrillero",
        descripcion: "Carnes jugosas a la parrilla con un ambiente rústico y familiar.",
        estilo: 2,
        imgURL: "/Restaurantes/3.webp",
        link: "/Restaurante3",
        handleLink: "Restaurante3",
        descripcionLarga:
            "El Fogón Parrillero es el lugar perfecto para los amantes de la carne. Sus cortes a la brasa, chorizos y costillas son preparados con técnicas tradicionales y acompañados de salsas artesanales.",
        ultraLargeDesc:
            "El Fogón Parrillero es mucho más que un restaurante: es un templo para los amantes de las carnes a la brasa donde la tradición parrillera se vive intensamente en cada rincón. Fundado en 1992 por el maestro parrillero Miguel Ángel Rodríguez, nuestro establecimiento ha perfeccionado el arte de la parrilla durante tres décadas, utilizando técnicas ancestrales combinadas con los mejores cortes de carne nacional. Nuestro secreto reside en la selección meticulosa de cortes premium - entre ellos el famoso churrasco dominicano, costillas de cerdo criollo y chuletas de cordero - que marinamos durante 24 horas en hierbas aromáticas locales como orégano orejón y cilantro. El carbón de marabú, cuidadosamente seleccionado, imparte ese sabor ahumado característico que distingue a nuestras parrilladas. Nuestras salsas son completamente artesanales: desde el chimichurri elaborado con perejil fresco y ajo hasta la barbacoa casera que slow-cokeamos por 8 horas. El ambiente rústico con mesas de madera maciza, decoración campestre y el aroma irresistible a leña y carne asada crea una experiencia sensorial completa. Los domingos son especiales con nuestra parrillada familiar ilimitada que incluye más de 15 tipos de carnes, embutidos artesanales y guarniciones tradicionales. En El Fogón Parrillero no solo servimos comida; creamos memorias alrededor del fuego que perduran en el paladar y el corazón.",
    },
    {
        id: 4,
        name: "La Ola Marina",
        descripcion: "Especialistas en mariscos frescos con sabor único.",
        estilo: 3,
        imgURL: "/Restaurantes/4.webp",
        link: "/Restaurante4",
        handleLink: "Restaurante4",
        descripcionLarga:
            "La Ola Marina trae a la mesa los mejores frutos del mar: camarones al ajillo, pescado frito, paella marinera y ceviches llenos de frescura. Todo con un ambiente costero relajado.",
        ultraLargeDesc:
            "La Ola Marina emerge como un auténtico santuario de los frutos del mar donde la frescura es nuestra religión y el sabor costero nuestro mantra. Desde 1987, hemos establecido relaciones directas con pescadores locales de las costas de Boca Chica, Bayahíbe y Las Terrenas, garantizando que cada producto marino llegue a nuestra cocina en menos de 12 horas desde su captura. Nuestra especialidad insignia es el pescado con coco, preparado con leche de coco fresco extraído artesanalmente y hierbas aromáticas que realzan su sabor natural sin enmascararlo. Los ceviches son una experiencia en sí mismos: desde el clásico ceviche de chillo hasta innovadoras creaciones como nuestro ceviche de pulpo con mango y ají limo. La paella marinera, cocinada en paelleras tradicionales sobre fuego de leña, se ha convertido en leyenda por su punto de azafrán y la perfecta textura del arroz bomba. El ambiente transporta inmediatamente a una playa caribeña: techos de palma, paredes adornadas con redes pesqueras auténticas, sonidos de olas de fondo y la brisa marina que entra por grandes ventanales. Nuestros chefs, liderados por el reconocido cocinero marinero Carlos Santos, dominan técnicas tanto tradicionales como vanguardistas, siempre respetando la esencia de cada ingrediente. Los viernes y sábados disfruta de nuestro 'Festival del Mar' con mariscos ilimitados y música en vivo que celebra nuestra herencia costera. La Ola Marina no es solo un restaurante; es una inmersión total en la cultura marina dominicana.",
    },
    {
        id: 5,
        name: "Pasta & Amore",
        descripcion: "Cocina italiana con recetas tradicionales y modernas.",
        estilo: 4,
        imgURL: "/Restaurantes/5.webp",
        link: "/Restaurante5",
        handleLink: "Restaurante5",
        descripcionLarga: "Pasta & Amore ofrece desde pastas artesanales hasta pizzas al horno de leña. Cada plato está pensado para transportarte directamente a Italia.",
        ultraLargeDesc:
            "Pasta & Amore representa la perfecta unión entre la pasión italiana y el corazón dominicano, creando una experiencia gastronómica que honra las tradiciones de la nonna con ingredientes locales de máxima calidad. Nuestro maestro pastiero, Giovanni Bianchi, llegado directamente de Nápoles en 2010, supervisa personalmente la elaboración diaria de más de 15 tipos de pasta fresca utilizando sémola de trigo duro importada y huevos campestres dominicanos. Las pastas secas se elaboran mediante el antiguo método de trafilado al bronce que garantiza esa textura porosa perfecta para absorber las salsas. Nuestras pizzas napolitanas siguen estrictamente los protocolos de la Associazione Verace Pizza Napoletana, con masa fermentada 72 horas y cocción en horno de leña de olivo que alcanza los 485°C. Los quesos son importados directamente de Italia - mozzarella di bufala campana, parmigiano reggiano aged 24 meses, pecorino romano - pero complementados con productos locales como el queso de hoja artesanal en nuestras creaciones fusion. La carta de vinos cuenta con más de 120 etiquetas exclusivas de todas las regiones italianas, seleccionadas personalmente por nuestro sommelier. El ambiente evoca una trattoria italiana auténtica con mesas de mármol, barriles de vino como decoración y el aroma embriagador de albahaca y ajo que inunda el espacio. Los domingos ofrecemos el tradicional 'Pranzo della Domenica' con menú familiar completo y música de ópera en vivo. Pasta & Amore no es solo comida italiana; es amor hecho pasta, tradición convertida en sabor y Italia vivida en República Dominicana.",
    },
    {
        id: 6,
        name: "La Muralla China",
        descripcion: "Auténtica cocina china con recetas clásicas y modernas.",
        estilo: 5,
        imgURL: "/Restaurantes/6.webp",
        link: "/Restaurante6",
        handleLink: "Restaurante6",
        descripcionLarga: "En La Muralla China puedes disfrutar de arroz frito, dumplings, rollitos primavera y platillos tradicionales hechos con auténticos sabores orientales.",
        ultraLargeDesc:
            "La Muralla China se erige como el bastión de la auténtica gastronomía oriental en República Dominicana, fusionando milenarias tradiciones culinarias chinas con el vibrante paladar caribeño. Desde 1985, nuestro restaurante ha sido pionero en introducir las técnicas ancestrales de la cocina cantonesa, sichuanesa y pekinesa, bajo la supervisión del maestro chef Wong Li, quien llegó desde Hong Kong con recetas familiares centenarias. Nuestro arroz frito Yangzhou se prepara con la técnica del wok hei que imparte ese sabor ahumado característico, usando arroz jazmín aged y ingredientes frescos cortados manualmente cada mañana. Los dim sum son nuestra especialidad: más de 30 variedades elaboradas artesanalmente por nuestro equipo de dim sum masters, destacando los har gow con camarones completos, siu mai de cerdo y cerdo asado, y los bollos bao al vapor con rellenos tradicionales. Contamos con un auténtico horno de leña para preparar el pato laqueado a la pekinesa según la receta original de la dinastía Ming, servido con pancakes caseros y salsa hoisin importada. El ambiente transporta a los palacios imperiales chinos con decoración tradicional, faroles de seda, y la clásica cerámica azul y blanca. Los fines de semana ofrecemos el servicio de Yum Cha con carritos de dim sum que recorren el salón, manteniendo viva esta tradición milenaria. La Muralla China es más que un restaurante; es un puente cultural entre Oriente y el Caribe, donde cada platillo cuenta una historia de sabores ancestrales.",
    },
    {
        id: 7,
        name: "El Sombrero Mexicano",
        descripcion: "Sabores intensos y picantes que representan a México.",
        estilo: 6,
        imgURL: "/Restaurantes/7.webp",
        link: "/Restaurante7",
        handleLink: "Restaurante7",
        descripcionLarga: "El Sombrero Mexicano ofrece tacos al pastor, enchiladas y guacamole fresco. Su ambiente alegre y colorido es ideal para disfrutar con amigos y familia.",
        ultraLargeDesc:
            "¡Ay, caramba! El Sombrero Mexicano es una fiesta para los sentidos donde la auténtica esencia de México cobra vida a través de sabores audaces, colores vibrantes y la calidez que caracteriza a la cultura azteca. Fundado en 1998 por la familia Mendoza originaria de Oaxaca, nuestro restaurante se ha convertido en el referente de la gastronomía mexicana en el Caribe. Nuestro trompo de pastor vertical, importado directamente de la Ciudad de México, gira lentamente durante horas impregnando la carne de cerdo con una marinada de chiles ancho y guajillo, achiote y especias secretas que han pasado por tres generaciones. Las tortillas son hechas a mano diariamente con maíz nixtamalizado, process que le da esa textura y sabor incomparables. El guacamole se prepara al momento en molcajetes de piedra volcánica con aguacates hass importados de Michoacán, tomate rojo, cebolla morada y cilantro fresco. Contamos con la barra de tequila y mezcal más extensa del país, con más de 150 variedades cuidadosamente seleccionadas, incluyendo añejos premium y mezcales artesanales de Oaxaca. El ambiente es una celebración constante: colores vibrantes, música mariachi en vivo los viernes y sábados, y decoración que rinde homenaje a la cultura mexicana con piezas artesanales traídas directamente de diferentes regiones de México. Los domingos ofrecemos nuestro famoso 'Brunch Mexicano' con chilaquiles, huevos rancheros y micheladas. ¡Arriba, arriba! El Sombrero Mexicano no es solo comida; es una experiencia que te transporta directamente al corazón de México.",
    },
    {
        id: 8,
        name: "Sabores del Medio Oriente",
        descripcion: "Cocina árabe con especias exóticas y sabores únicos.",
        estilo: 7,
        imgURL: "/Restaurantes/8.webp",
        link: "/Restaurante8",
        handleLink: "Restaurante8",
        descripcionLarga: "Este restaurante te invita a probar shawarma, hummus, falafel y kebabs preparados con recetas auténticas del Medio Oriente.",
        ultraLargeDesc:
            "Sabores del Medio Oriente es un oasis gastronómico donde los aromas de las especias milenarias y las tradiciones culinarias árabes se fusionan con la calidez dominicana. Desde 2001, nuestro restaurante ha sido el embajador de la rica herencia culinaria de Líbano, Siria, Palestina y Turquía en el corazón del Caribe. El chef Ahmad Al-Fayed, proveniente de una larga estirpe de cocineros libaneses, supervisa cada preparación con estándares rigurosos de autenticidad. Nuestro shawarma se elabora con capas de carne de cordero y res marinadas por 48 horas en una mezcla secreta de 15 especias, asándose lentamente en el trompo tradicional hasta alcanzar la perfección. El hummus se prepara diariamente con garbanzos remojados artesanalmente, tahini importado del Líbano y aceite de oliva extra virgen de la variedad picual. Los falafels se fríen al momento usando garbanzos remojados (nunca cocidos) que garantizan esa textura crujiente por fuera y esponjosa por dentro. El ambiente evoca los majestuosos palacios árabes con arcos moriscos, alfombras persas auténticas, lámparas de mosaico y la tradicional decoración con narguiles y piezas de arte oriental. Los jueves y sábados disfruta de nuestro espectáculo de danza belly dance mientras saboreas nuestra selección de meze que incluye más de 20 variedades de entradas tradicionales. La carta incluye especialidades como el mansaf jordano, el kabsa saudí y el maqluba palestino, preparados con recetas ancestrales. Sabores del Medio Oriente es un viaje sensorial a través de las rutas de las especias y los sabores que han conquistado paladares por siglos.",
    },
    {
        id: 9,
        name: "Tokyo Fusion",
        descripcion: "La elegancia de la cocina japonesa en cada plato.",
        estilo: 8,
        imgURL: "/Restaurantes/9.webp",
        link: "/Restaurante9",
        handleLink: "Restaurante9",
        descripcionLarga: "Tokyo Fusion mezcla lo mejor de la tradición japonesa con un toque contemporáneo. Sushi, ramen y tempuras en un ambiente minimalista.",
        ultraLargeDesc:
            "Tokyo Fusion representa la perfecta simbiosis entre el respeto por las milenarias tradiciones culinarias japonesas y la innovación contemporánea, creando una experiencia gastronómica que honra el pasado mientras abraza el futuro. Bajo la dirección del chef Hiroshi Tanaka, formado en los prestigiosos restaurantes de Ginza (Tokio), nuestro establecimiento ofrece un recorrido por las diversas prefecturas de Japón a través del paladar. El sushi bar es el corazón de Tokyo Fusion, donde nuestros itamae con más de 15 años de experiencia preparan nigiri y sashimi con pescados importados directamente del mercado de Tsukiji: toro de atún bluefin, hamachi de aguas profundas, y uni fresco de Hokkaido. El ramen se elabora con caldos que slow-cokeamos por más de 18 horas, usando huesos de cerdo berkshire y pollo jidori, resultando en una broth de profundidad y complejidad incomparables. Las tempuras mantienen la tradición edo-style con una masa etérea y ligera que creamos usando agua helada y harina de arroz especial importada. El ambiente refleja la estética japonesa contemporánea: líneas limpias, madera de ciprés hinoki, iluminación tenue y privacidad mediante shoji screens que crean espacios íntimos. Contamos con una exclusiva sala tatami para cenas kaiseki auténticas que requieren reservación previa. La barra de sake ofrece más de 40 variedades premium, incluyendo daiginjo y junmai ginjo cuidadosamente seleccionados por nuestro sake sommelier. Tokyo Fusion no es solo una comida; es una inmersión en la cultura japonesa a través de los cinco sentidos, donde cada detalle importa y cada bocado cuenta una historia.",
    },
    {
        id: 10,
        name: "Green Life",
        descripcion: "Comida vegana fresca, saludable y deliciosa.",
        estilo: 9,
        imgURL: "/Restaurantes/10.webp",
        link: "/Restaurante10",
        handleLink: "Restaurante10",
        descripcionLarga:
            "Green Life ofrece ensaladas creativas, hamburguesas veganas, smoothies y postres sin ingredientes de origen animal. Perfecto para quienes buscan cuidar su salud sin sacrificar sabor.",
        ultraLargeDesc:
            "Green Life nació de una revolucionaria visión: demostrar que la alimentación vegana puede ser extraordinariamente deliciosa, nutricionalmente completa y ambientalmente sostenible, sin comprometer el placer gastronómico. Nuestro fundador, el chef español Carlos Verde, combinó su expertise en cocina de plant-based con los exuberantes productos locales dominicanos para crear un concepto único en el Caribe. Trabajamos directamente con una red de más de 30 agricultores orgánicos locales que nos proveen diariamente de vegetales, frutas tropicales y hierbas cultivadas sin pesticidas ni químicos. Nuestras 'carnes' vegetales son elaboradas artesanalmente usando técnicas de fermentación y texturización: el jackfruit young para模拟 pulled pork, los hongos ostras ahumados para replicar la textura del bacon, y la mezcla de legumbres y nueces para nuestras hamburguesas gourmet. Los quesos veganos son fermentados in-house usando anacardos orgánicos y cultivos probióticos que desarrollan sabores complejos y texturas cremosas. El ambiente refleja nuestra filosofía: diseño bioclimático con materiales reciclados, iluminación LED de bajo consumo, y un jardín interior con hierbas aromáticas que los clientes pueden cosechar al momento. Nuestra carta cambia estacionalmente para aprovechar la máxima frescura de los productos, e incluye innovaciones como el 'ceviche' de hearts of palm, las 'carnitas' de banana verde, y los postres raw hechos sin horno usando solo deshidratación a baja temperatura. Green Life es más que un restaurante vegano; es un estilo de vida, una declaración de principios y un santuario para quienes creen que se puede comer delicioso mientras se cuida el planeta y se respeta a todos los seres vivos.",
    },
    {
        id: 11,
        name: "El Sazón Dominicano",
        descripcion: "Comida típica dominicana hecha con amor casero.",
        estilo: 0,
        imgURL: "/Restaurantes/11.webp",
        link: "/Restaurante11",
        handleLink: "Restaurante11",
        descripcionLarga: "Aquí encontrarás la auténtica bandera dominicana, mangú con los tres golpes, sancochos y platos tradicionales que saben a hogar.",
        ultraLargeDesc:
            "El Sazón Dominicano es el corazón palpitante de la cocina criolla auténtica, un lugar donde las recetas ancestrales se preservan con devoción y cada plato cuenta la historia gastronómica de nuestra isla. Fundado en 1982 por la matriarca Doña Carmen, nuestra cocina mantiene vivas las técnicas tradicionales que han pasado por generaciones en familias dominicanas. Nuestro sancocho de siete carnes se prepara en ollas de hierro fundido durante horas, permitiendo que los sabores del res, cerdo, pollo, longaniza, costilla, mondongo y chivo se fusionen en una symphony de sabores que es patrimonio nacional. El mangú se elabora exclusivamente con plátanos verdes machucados en pilón de madera, preservando esa textura cremosa que caracteriza el desayuno dominicano auténtico. La 'bandera' - nuestro plato insignia - sigue estrictamente la tradición: arroz blanco grano entero, habichuelas rojas guisadas con culantro y auyama, y carne de res o pollo marinada en naranja agria y hierbas locales. El ambiente recrea el típico comedor de una casa dominicana de los años 70: mesas de madera de caoba, sillas de mimbre, paredes adornadas con fotos históricas de República Dominicana y el inconfundible sonido de bachata y merengue de antaño. Los domingos se convierte en punto de reunión familiar donde abuelos, padres y nietos comparten nuestras fuentes de locrio, pastelón de maduros y habichuelas con dulce. El Sazón Dominicano no es un restaurante; es el hogar culinario de todo dominicano que extraña los sabores de su tierra.",
    },
    {
        id: 12,
        name: "Burguer House",
        descripcion: "Hamburguesas artesanales con combinaciones únicas.",
        estilo: 1,
        imgURL: "/Restaurantes/12.webp",
        link: "/Restaurante12",
        handleLink: "Restaurante12",
        descripcionLarga: "Burguer House se especializa en hamburguesas gourmet con ingredientes frescos, acompañadas de papas fritas crujientes y salsas secretas.",
        ultraLargeDesc:
            "Burguer House ha redefinido el concepto de hamburguesa artesanal en República Dominicana, elevando este clásico norteamericano a niveles de gourmet con ingredientes premium y técnicas culinarias innovadoras. Nuestro fundador, el chef Roberto Martínez, después de formarse en los mejores burger bars de Nueva York y California, regresó a Santo Domingo con la misión de crear la hamburguesa perfecta. Nuestra carne proviene de reses Angus criadas en pastos de la Cordillera Central, molida diariamente en nuestro local para garantizar esa textura jugosa y ese sabor intenso. Cada burger pesa exactamente 180g y se cocina a la parrilla de carbón que imparte ese sello ahumado característico. Los panes brioche son horneados cada mañana con leche orgánica y mantequilla francesa, resultando en esa miga esponjosa y corteza ligeramente crujiente. Nuestras salsas signature son legendarias: desde la 'Dominicana' con mamón y cilantro hasta la 'Caribbean Heat' con habaneros maduros y mango. Las papas fritas se cortan manualmente en tres estilos diferentes: clásicas, sweet potato y yuca, y se fríen en aceite de aguacate a temperatura controlada. El ambiente industrial-chic con mesas de concreto, iluminación con tubos Edison y música blues crea el escenario perfecto para disfrutar de nuestras creaciones. La carta incluye más de 15 tipos de hamburguesas, desde la clásica 'House Burger' hasta la extravagante 'Tropical Paradise' con piña caramelizada y bacon de coco. Burguer House no es una hamburguesería; es un templo para los amantes de la buena carne donde cada bocado es una explosión de sabores cuidadosamente equilibrados.",
    },
    {
        id: 13,
        name: "La Brasa Viva",
        descripcion: "Parrillada al carbón con carnes y embutidos irresistibles.",
        estilo: 2,
        imgURL: "/Restaurantes/13.webp",
        link: "/Restaurante13",
        handleLink: "Restaurante13",
        descripcionLarga: "La Brasa Viva ofrece cortes premium cocinados al carbón con un sabor ahumado inigualable, acompañados de ensaladas y guarniciones clásicas.",
        ultraLargeDesc:
            "La Brasa Viva es el epicentro de la cultura parrillera en República Dominicana, donde el fuego, la carne y la pasión se unen para crear experiencias memorables alrededor de las brasas. Nuestro asador principal, una imponente estructura de hierro forjado de 4 metros de largo, es el altar donde transformamos cortes premium en obras maestras de la parrilla. Trabajamos exclusivamente con carnes maduradas entre 21-28 días que desarrollan sabores intensos y texturas butter-tender. Nuestro churrasco argentino se marina 48 horas en chimichurri tradicional, mientras que las costillas de cerdo slow-smokeamos por 6 horas con madera de guayabo que imparte un aroma dulce y ahumado. Los embutidos son elaborados artesanalmente por nuestro maestro charcutero: chorizos criollos, morcillas con arroz y butifarras catalanas que honran diferentes tradiciones carnívoras. El sistema de parrillas incluye zonas de calor directo e indirecto, permitiendo cocinar cada corte a su temperatura ideal perfecta. Las guarniciones siguen la filosofión 'less is more': ensaladas frescas de la huerta, papas rústicas con romero y provenzal, y vegetales asados que realzan las carnes. El ambiente rústico-elegante con vigas de madera vista, paredes de piedra natural y iluminación cálida crea el escenario perfecto para noches inolvidables. Los viernes tenemos 'Noche de Asador' con parrillada completa y show de cuchillos, mientras los sábados son para nuestro famoso 'Matambre a la estaca' que se sirve directamente del asador. La Brasa Viva no cocina carne; celebra rituales ancestrales alrededor del fuego donde cada corte cuenta una historia de tradición y sabor.",
    },
    {
        id: 14,
        name: "Costa Azul",
        descripcion: "Un rincón marino con los mejores mariscos frescos.",
        estilo: 3,
        imgURL: "/Restaurantes/14.webp",
        link: "/Restaurante14",
        handleLink: "Restaurante14",
        descripcionLarga: "Costa Azul es el lugar perfecto para probar langostas, ceviches y arroces marineros mientras disfrutas de un ambiente playero.",
        ultraLargeDesc:
            "Costa Azul captura la esencia misma del mar Caribe, ofreciendo una experiencia gastronómica donde la frescura de los frutos marinos se combina con técnicas culinarias que realzan su sabor natural. Ubicado estratégicamente frente al malecón, nuestro restaurante ofrece vistas panorámicas al océano mientras disfrutas de los tesoros que este nos brinda. Nuestra pesca del día llega directamente de las embarcaciones locales que faenan en las ricas aguas de la plataforma continental dominicana, garantizando que langostas, camarones, pulpos y peces lleguen a nuestra cocina en su punto óptimo de frescura. El ceviche bar es nuestra joya principal, donde preparamos más de 12 variedades que van desde el clásico peruano hasta innovadoras creaciones como el ceviche de dorado con leche de tigre de maracuyá. Las langostas se mantienen vivas en tanques de agua marina hasta el momento de su preparación, ya sea a la plancha con mantequilla de ajo o gratinadas con queso artesanal. Los arroces marineros se cocinan en paelleras sobre fuego de leña, usando caldo de pescado slow-cooked por 12 horas que imparte una profundidad de sabor incomparable. El ambiente costero elegante combina decoración náutica con comodidad moderna: techos altos, tonos azules y blancos, y amplios ventanales que aprovechan la brisa marina. Los atardeceres en Costa Azul son legendarios, con nuestro bar de mojitos y daiquiris acompañando la puesta de sol sobre el Caribe. Costa Azul no es un restaurante de mariscos; es un pedazo del mar transformado en experiencia gastronómica donde cada ola trae nuevos sabores.",
    },
    {
        id: 15,
        name: "La Nonna Italiana",
        descripcion: "Recetas italianas tradicionales como las hacía la abuela.",
        estilo: 4,
        imgURL: "/Restaurantes/15.webp",
        link: "/Restaurante15",
        handleLink: "Restaurante15",
        descripcionLarga: "En La Nonna Italiana se sirven pastas frescas hechas a mano, lasañas al horno y postres típicos como el tiramisú.",
        ultraLargeDesc:
            "La Nonna Italiana es el hogar lejano de todos los amantes de la auténtica cocina italiana, donde las recetas de la abuela cobran vida con el amor y la paciencia que caracterizan la tradición culinaria de la bota. Nuestra nonna espiritual, la signora Rosanna Bianchi, supervisa cada preparación desde su pequeña pueblo en las colinas de Toscana, asegurando que cada plato mantenga la esencia de la cucina povera italiana. Las pastas frescas se elaboran diariamente usando harina 00 importada de Italia y huevos camperos, pasando por el proceso tradicional de amasado, reposo y cortado manual que garantiza esa textura perfectamente al dente. Nuestra lasaña bolognese sigue la receta original de la signora Bianchi: 12 capas de pasta fresca intercaladas con ragú slow-cooked por 6 horas, besciamella cremosa y parmigiano-reggiano aged. Los sauces son nuestra obsesión: desde el pomodoro preparado con tomates san marzano DOP hasta el pesto genovese hecho en mortero de mármol con albahaca fresca, piñones de la Toscana y aceite de oliva extra virgen. El ambiente recrea una casa de campo italiana: mesas de madera rústica, estanterías con conservas caseras, y el aroma embriagador de ajo, albahaca y tomate que inunda cada rincón. Los domingos son día de famiglia con nuestro menú de siete tiempos que incluye antipasti, primi, secondi y dolci servidos al estilo tradicional. La Nonna Italiana no es un restaurante; es la cocina de la abuela que todos deseamos tener, donde cada plato está hecho con amore y ogni boccone è una festa.",
    },
    {
        id: 16,
        name: "Dragón Dorado",
        descripcion: "Cocina china con platos abundantes y llenos de sabor.",
        estilo: 5,
        imgURL: "/Restaurantes/16.webp",
        link: "/Restaurante16",
        handleLink: "Restaurante16",
        descripcionLarga: "El Dragón Dorado es conocido por su pollo agridulce, chow mein y sopas tradicionales, siempre en porciones generosas.",
        ultraLargeDesc:
            "Dragón Dorado es el emblema de la auténtica cocina china en la ciudad, donde la tradición y la abundancia se fusionan para ofrecer una experiencia culinaria inolvidable. Fundado en 1990 por la familia Liu, el restaurante ha mantenido vivas las recetas ancestrales de la región de Cantón y Sichuan, adaptándolas con ingredientes frescos locales. Nuestro pollo agridulce es preparado con una salsa secreta que equilibra perfectamente el dulzor y la acidez, mientras que el chow mein se saltea en wok a fuego alto para lograr esa textura crujiente y sabor ahumado característico. Las sopas, como la de wantán y la de maíz con pollo, se cocinan lentamente durante horas para extraer el máximo sabor de cada ingrediente. El ambiente está decorado con dragones dorados, faroles rojos y murales que evocan la China imperial, creando un espacio acogedor y familiar. Los chefs, formados en Hong Kong, dominan el arte del dim sum, ofreciendo una variedad de bocados al vapor y fritos que deleitan a grandes y chicos. Los fines de semana, el restaurante se llena de familias que disfrutan de banquetes con platos servidos al centro, siguiendo la tradición china de compartir la comida. Dragón Dorado no es solo un restaurante, es un puente cultural que acerca los sabores milenarios de China a cada comensal, haciendo de cada visita una celebración de la abundancia y la hospitalidad oriental.",
    },
    {
        id: 17,
        name: "La Cantina Azteca",
        descripcion: "El sabor mexicano más auténtico en cada bocado.",
        estilo: 6,
        imgURL: "/Restaurantes/17.webp",
        link: "/Restaurante17",
        handleLink: "Restaurante17",
        descripcionLarga: "En La Cantina Azteca se disfrutan tacos de carnitas, burritos y margaritas en un ambiente festivo y colorido.",
        ultraLargeDesc:
            "La Cantina Azteca es el corazón de la cultura mexicana en la ciudad, un lugar donde los sabores intensos y las tradiciones ancestrales se celebran en cada plato. Fundada por la familia Ramírez, originaria de Puebla, la cantina ofrece una carta que recorre México de norte a sur: tacos de carnitas cocidos lentamente en su propia grasa, burritos rellenos de frijoles negros y carne sazonada con especias importadas, y margaritas preparadas con tequila 100% agave. El ambiente es una explosión de colores, con murales de calaveras, papel picado y música de mariachi en vivo los fines de semana. Las tortillas se hacen a mano cada día, y el guacamole se prepara al momento en molcajetes de piedra volcánica. La barra cuenta con una amplia selección de tequilas y mezcales, ideales para acompañar los platos más picantes. Los postres, como el pastel de tres leches y los churros con chocolate, cierran la experiencia con un toque dulce y tradicional. La Cantina Azteca es más que un restaurante: es una fiesta continua donde la alegría, la hospitalidad y el auténtico sabor mexicano se viven en cada rincón, invitando a todos a disfrutar de la riqueza gastronómica de México.",
    },
    {
        id: 18,
        name: "Oasis Árabe",
        descripcion: "Platos tradicionales del Medio Oriente con especias exóticas.",
        estilo: 7,
        imgURL: "/Restaurantes/18.webp",
        link: "/Restaurante18",
        handleLink: "Restaurante18",
        descripcionLarga: "Oasis Árabe ofrece cordero al horno, tabule y baklava, todo preparado con recetas auténticas.",
        ultraLargeDesc:
            "Oasis Árabe es un refugio de sabores y aromas del Medio Oriente, donde cada plato es una invitación a viajar por las antiguas rutas de las especias. Fundado por la familia Al-Masri, el restaurante se especializa en cordero al horno marinado con hierbas y especias traídas directamente de Damasco, tabule fresco con perejil, tomate y bulgur, y baklava artesanal bañado en miel de azahar. El ambiente evoca los palacios árabes, con lámparas de mosaico, alfombras persas y música tradicional que acompaña la experiencia. Los chefs, herederos de recetas familiares transmitidas por generaciones, preparan hummus, falafel y kebabs con ingredientes frescos y técnicas ancestrales. Los jueves y sábados, el restaurante ofrece espectáculos de danza del vientre, sumergiendo a los comensales en la magia de Oriente. La carta de tés incluye mezclas de menta, cardamomo y canela, ideales para acompañar los dulces árabes. Oasis Árabe es más que un restaurante: es un viaje sensorial a través de la hospitalidad, la tradición y la riqueza culinaria del Medio Oriente, donde cada comida es una celebración de la vida y la cultura.",
    },
    {
        id: 19,
        name: "Samurai Sushi",
        descripcion: "El arte japonés del sushi llevado a la perfección.",
        estilo: 8,
        imgURL: "/Restaurantes/19.webp",
        link: "/Restaurante19",
        handleLink: "Restaurante19",
        descripcionLarga: "Samurai Sushi combina tradición y creatividad, ofreciendo nigiris, rolls especiales y ramen artesanal.",
        ultraLargeDesc:
            "Samurai Sushi es el templo de la gastronomía japonesa, donde la precisión, la frescura y la creatividad se unen para ofrecer una experiencia única. Fundado por el chef Kenji Nakamura, formado en Tokio, el restaurante se especializa en sushi preparado al momento con pescados importados y arroz de grano corto sazonado a la perfección. Los nigiris y sashimis son cortados con maestría, mientras que los rolls especiales fusionan ingredientes tradicionales japoneses con toques caribeños. El ramen artesanal se cocina durante horas para lograr un caldo profundo y sabroso, acompañado de fideos frescos y toppings seleccionados. El ambiente minimalista, con madera clara, paneles de papel de arroz y una barra de sushi abierta, invita a la contemplación y el disfrute pausado. La carta de sakes y cervezas japonesas complementa la experiencia, mientras que los postres, como el mochi y el dorayaki, cierran la comida con dulzura. Samurai Sushi no es solo un restaurante: es una oda al arte culinario japonés, donde cada bocado es una muestra de respeto por la tradición y la innovación.",
    },
    {
        id: 20,
        name: "Verde Vivo",
        descripcion: "Una propuesta vegana fresca y sostenible.",
        estilo: 9,
        imgURL: "/Restaurantes/20.webp",
        link: "/Restaurante20",
        handleLink: "Restaurante20",
        descripcionLarga: "Verde Vivo apuesta por platos nutritivos como ensaladas coloridas, bowls energéticos y jugos naturales.",
        ultraLargeDesc:
            "Verde Vivo es el paraíso de la alimentación consciente, donde la frescura, la sostenibilidad y el sabor se encuentran en cada plato. Fundado por la chef Laura Gómez, apasionada por la cocina plant-based, el restaurante trabaja con agricultores locales para ofrecer ingredientes orgánicos y de temporada. Las ensaladas son una explosión de colores y texturas, los bowls energéticos combinan granos, legumbres y vegetales asados, y los jugos naturales se preparan al momento con frutas frescas. El ambiente es luminoso y acogedor, con plantas colgantes, muebles reciclados y una terraza rodeada de vegetación. La carta cambia según la estación, incorporando superalimentos y opciones sin gluten ni azúcar refinada. Los postres, como el cheesecake de anacardos y los brownies de cacao puro, demuestran que lo saludable también puede ser delicioso. Verde Vivo es más que un restaurante: es un movimiento que promueve el bienestar, el respeto por el medio ambiente y el placer de comer bien, invitando a todos a descubrir el poder de la cocina vegana.",
    },
    {
        id: 21,
        name: "El Patio Criollo",
        descripcion: "Platos dominicanos típicos en un ambiente acogedor.",
        estilo: 0,
        imgURL: "/Restaurantes/21.webp",
        link: "/Restaurante21",
        handleLink: "Restaurante21",
        descripcionLarga: "El Patio Criollo ofrece mofongo, chicharrones, tostones y sancochos preparados con el auténtico sazón local.",
        ultraLargeDesc:
            "El Patio Criollo es el rincón donde la tradición dominicana cobra vida en cada plato, evocando los sabores y aromas de la cocina casera. Fundado por la familia Rodríguez, el restaurante se especializa en mofongo de plátano verde machacado con chicharrón, chicharrones crujientes y tostones dorados, todo preparado con ingredientes frescos y técnicas heredadas de generación en generación. El sancocho, cocido a fuego lento, es el plato estrella de los domingos, reuniendo a familias y amigos alrededor de la mesa. El ambiente es cálido y familiar, con mesas de madera, paredes decoradas con fotos antiguas y música típica que acompaña la experiencia. Los postres, como el dulce de leche cortada y el majarete, cierran la comida con un toque de nostalgia. El Patio Criollo no es solo un restaurante: es un homenaje a la cultura dominicana, un espacio donde cada bocado es un viaje al pasado y una celebración de la identidad nacional.",
    },
    {
        id: 22,
        name: "Pizza Express",
        descripcion: "Pizzas rápidas, crujientes y con ingredientes frescos.",
        estilo: 1,
        imgURL: "/Restaurantes/22.webp",
        link: "/Restaurante22",
        handleLink: "Restaurante22",
        descripcionLarga: "Pizza Express prepara pizzas al momento, con masa fina y combinaciones clásicas y modernas.",
        ultraLargeDesc:
            "Pizza Express es el destino favorito de los amantes de la pizza que buscan rapidez sin sacrificar calidad. Fundado por el chef italiano Marco Rossi, el restaurante utiliza una masa fina fermentada durante 24 horas para lograr una base crujiente y ligera. Las pizzas se preparan al momento en horno de piedra, con ingredientes frescos y combinaciones que van desde la clásica margarita hasta creaciones innovadoras con ingredientes locales. El ambiente es moderno y dinámico, ideal para familias, grupos de amigos y quienes buscan una comida deliciosa en poco tiempo. La carta incluye opciones vegetarianas, veganas y sin gluten, así como calzones y focaccias recién horneadas. Los postres, como el tiramisú y la panna cotta, completan la experiencia italiana. Pizza Express no es solo una pizzería: es una celebración de la pizza artesanal, donde la rapidez y el sabor van de la mano para satisfacer todos los antojos.",
    },
    {
        id: 23,
        name: "Parrilla del Norte",
        descripcion: "Cortes de carne asados al estilo tradicional.",
        estilo: 2,
        imgURL: "/Restaurantes/23.webp",
        link: "/Restaurante23",
        handleLink: "Restaurante23",
        descripcionLarga: "La Parrilla del Norte se especializa en costillas, lomos y embutidos, acompañados de guarniciones abundantes.",
        ultraLargeDesc:
            "Parrilla del Norte es el santuario de los carnívoros, donde la pasión por la carne asada se vive en cada detalle. Fundada por el asador argentino Gustavo Fernández, el restaurante ofrece costillas jugosas, lomos tiernos y embutidos artesanales preparados en una parrilla de leña que imparte un sabor ahumado inconfundible. Las guarniciones, como las papas rústicas y las ensaladas frescas, complementan a la perfección los cortes de carne. El ambiente es rústico y acogedor, con mesas largas de madera, paredes de ladrillo y una chimenea central que invita a compartir. Los fines de semana, la parrilla se convierte en el centro de reuniones familiares y celebraciones, con música en vivo y un ambiente festivo. Los postres, como el flan casero y el dulce de leche, cierran la experiencia con un toque dulce y tradicional. Parrilla del Norte no es solo un restaurante: es un homenaje a la cultura del asado, donde cada comida es una fiesta de sabor y camaradería.",
    },
    {
        id: 24,
        name: "Mar y Sol",
        descripcion: "Mariscos frescos con vista al mar.",
        estilo: 3,
        imgURL: "/Restaurantes/24.webp",
        link: "/Restaurante24",
        handleLink: "Restaurante24",
        descripcionLarga: "Mar y Sol ofrece camarones, ostras y pescados frescos servidos en un ambiente playero único.",
        ultraLargeDesc:
            "Mar y Sol es el refugio perfecto para los amantes de los mariscos, donde la frescura y la vista al mar se combinan para crear una experiencia inolvidable. Fundado por la familia Suárez, el restaurante recibe diariamente camarones, ostras y pescados frescos de pescadores locales, garantizando la máxima calidad en cada plato. El ceviche de camarón, las ostras al natural y el pescado a la plancha son los favoritos de la casa, preparados con recetas sencillas que resaltan el sabor del mar. El ambiente playero, con mesas al aire libre, sombrillas de palma y una brisa constante, invita a relajarse y disfrutar del paisaje. La carta de cócteles incluye mojitos, caipirinhas y jugos tropicales, ideales para acompañar los mariscos. Los postres, como la tarta de coco y el flan de piña, cierran la comida con un toque dulce y refrescante. Mar y Sol no es solo un restaurante: es una escapada al paraíso, donde cada comida es una celebración de la vida junto al mar.",
    },
    {
        id: 25,
        name: "Roma Gourmet",
        descripcion: "Cocina italiana elegante y sofisticada.",
        estilo: 4,
        imgURL: "/Restaurantes/25.webp",
        link: "/Restaurante25",
        handleLink: "Restaurante25",
        descripcionLarga: "Roma Gourmet se distingue por su pasta rellena, risottos cremosos y vinos importados.",
        ultraLargeDesc:
            "Roma Gourmet es el destino de los paladares exigentes que buscan la elegancia y la sofisticación de la alta cocina italiana. Fundado por el chef Alessandro Conti, formado en Roma, el restaurante ofrece pastas rellenas hechas a mano, risottos cremosos y una selección de vinos importados de las mejores regiones de Italia. El ambiente es refinado, con manteles blancos, candelabros y una decoración inspirada en los palacios romanos. La carta incluye antipastos, carpaccios y platos principales que combinan ingredientes locales con técnicas tradicionales italianas. Los postres, como el tiramisú y la panna cotta, son preparados al momento para garantizar frescura y sabor. El servicio es atento y personalizado, haciendo que cada visita sea una experiencia memorable. Roma Gourmet no es solo un restaurante: es un viaje a la Italia más exclusiva, donde cada plato es una obra de arte y cada comida una celebración del buen gusto.",
    },
    {
        id: 26,
        name: "Panda Feliz",
        descripcion: "Platos chinos abundantes y llenos de tradición.",
        estilo: 5,
        imgURL: "/Restaurantes/26.webp",
        link: "/Restaurante26",
        handleLink: "Restaurante26",
        descripcionLarga: "Panda Feliz es conocido por su arroz tres delicias, pato pekinés y platos familiares servidos en grandes porciones.",
        ultraLargeDesc:
            "Panda Feliz es el lugar donde la tradición china y la generosidad se encuentran en cada plato, ofreciendo una experiencia culinaria que celebra la abundancia y el sabor. Fundado por la familia Zhang, el restaurante se especializa en arroz tres delicias salteado al wok, pato pekinés asado a la perfección y una variedad de platos familiares servidos en grandes porciones para compartir. El ambiente es alegre y colorido, con decoraciones típicas chinas, faroles rojos y música tradicional que acompaña la comida. Los chefs, formados en Shanghái, preparan dim sum, sopas y fideos con recetas transmitidas de generación en generación. Los postres, como los bollos de loto y el flan de huevo, cierran la experiencia con un toque dulce y exótico. Panda Feliz no es solo un restaurante: es un homenaje a la hospitalidad china, donde cada comida es una oportunidad para compartir, celebrar y disfrutar de la riqueza culinaria de Oriente.",
    },
    {
        id: 27,
        name: "La Hacienda Mexicana",
        descripcion: "Un rincón para disfrutar de la auténtica cocina mexicana.",
        estilo: 6,
        imgURL: "/Restaurantes/27.webp",
        link: "/Restaurante27",
        handleLink: "Restaurante27",
        descripcionLarga: "La Hacienda Mexicana ofrece quesadillas, pozole y tequila en un espacio festivo y acogedor.",
        ultraLargeDesc:
            "La Hacienda Mexicana es el rincón donde la tradición y la alegría de México se viven en cada detalle. Fundada por la chef Guadalupe Torres, originaria de Jalisco, el restaurante ofrece quesadillas de maíz hechas a mano, pozole cocido a fuego lento y una selección de tequilas y mezcales que invitan a brindar. El ambiente es festivo y acogedor, con paredes de colores vivos, sombreros charros y música ranchera en vivo los fines de semana. La carta incluye tacos, enchiladas y guacamole preparado al momento, así como postres típicos como el pastel de elote y las cajetas. Los platos se sirven al centro para compartir, siguiendo la tradición mexicana de la comida en familia. La Hacienda Mexicana no es solo un restaurante: es una celebración de la cultura, la hospitalidad y el sabor de México, donde cada visita es una fiesta para los sentidos.",
    },
    {
        id: 28,
        name: "Delicias Árabes",
        descripcion: "Platos árabes tradicionales llenos de especias y sabor.",
        estilo: 7,
        imgURL: "/Restaurantes/28.webp",
        link: "/Restaurante28",
        handleLink: "Restaurante28",
        descripcionLarga: "Delicias Árabes ofrece shawarma, arroz con cordero y dulces árabes hechos a mano.",
        ultraLargeDesc:
            "Delicias Árabes es el destino ideal para quienes buscan los sabores intensos y exóticos de la cocina del Medio Oriente. Fundado por la familia Haddad, el restaurante se especializa en shawarma de cordero asado lentamente, arroz especiado con frutos secos y una variedad de dulces árabes hechos a mano, como el baklava y los maamoul. El ambiente es cálido y acogedor, con alfombras, cojines y lámparas de colores que transportan a los comensales a un auténtico salón árabe. Los chefs preparan hummus, tabule y falafel con ingredientes frescos y especias importadas, garantizando autenticidad en cada bocado. Los tés aromáticos y las infusiones de hierbas completan la experiencia, invitando a la relajación y el disfrute. Delicias Árabes no es solo un restaurante: es un viaje culinario por las tierras de las mil y una noches, donde cada plato cuenta una historia de tradición y hospitalidad.",
    },
    {
        id: 29,
        name: "Sakura Garden",
        descripcion: "Un jardín japonés lleno de tradición y sabor.",
        estilo: 8,
        imgURL: "/Restaurantes/29.webp",
        link: "/Restaurante29",
        handleLink: "Restaurante29",
        descripcionLarga: "Sakura Garden ofrece sushi fresco, sopas japonesas y postres como el mochi en un ambiente zen.",
        ultraLargeDesc:
            "Sakura Garden es un oasis de paz y tradición japonesa, donde la belleza del jardín de cerezos se refleja en cada plato. Fundado por el chef Hiroshi Sato, el restaurante ofrece sushi fresco preparado al momento, sopas japonesas como el miso y el udon, y postres delicados como el mochi y el dorayaki. El ambiente es zen, con jardines interiores, fuentes de agua y una decoración minimalista que invita a la contemplación. La carta incluye una selección de tés verdes y sakes premium, ideales para acompañar la comida. Los chefs, formados en Kioto, preparan cada plato con precisión y respeto por la tradición, garantizando una experiencia auténtica. Sakura Garden no es solo un restaurante: es un refugio para el alma, un espacio donde la gastronomía y la naturaleza se unen para ofrecer momentos de serenidad y placer.",
    },
    {
        id: 30,
        name: "Planeta Verde",
        descripcion: "Comida vegana creativa para un estilo de vida saludable.",
        estilo: 9,
        imgURL: "/Restaurantes/30.webp",
        link: "/Restaurante30",
        handleLink: "Restaurante30",
        descripcionLarga: "Planeta Verde presenta bowls, wraps y smoothies que combinan sabor, salud y sostenibilidad.",
        ultraLargeDesc:
            "Planeta Verde es el epicentro de la cocina vegana creativa, donde la salud, el sabor y la sostenibilidad se dan la mano en cada plato. Fundado por la chef Camila Duarte, el restaurante apuesta por ingredientes locales, orgánicos y de comercio justo, transformándolos en bowls nutritivos, wraps llenos de color y smoothies energéticos. El ambiente es moderno y ecológico, con muebles reciclados, plantas por doquier y una carta que cambia según la temporada. Los platos están diseñados para aportar todos los nutrientes necesarios, sin renunciar al placer de comer bien. Los postres, como el brownie de batata y el cheesecake de coco, demuestran que la cocina vegana puede ser deliciosa y sorprendente. Planeta Verde no es solo un restaurante: es un compromiso con el planeta y el bienestar, una invitación a descubrir nuevas formas de alimentarse y disfrutar de la vida.",
    },
];

export default RESTAURANT;
